server:
  port: 8000
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


#################
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: test00
    password: test00


  devtools:
    # Live Reload
    livereload:
      enabled: true
  level:
    root: info
    com.web.springbootpro: debug


mybatis:
  mapper-locations: classpath:mapper/*.xml
  mybatis:
     config-location: classpath:/mybatis/mapper/mybatis-config.xml

    #config-location: classpath:mybatis-config.xml
    #configuration:
    # map-underscore-to-camel-case: true

cos:
  key: cos1234

